name: Deploy to DigitalOcean

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Deploy to DigitalOcean
              env:
                  PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
                  HOST: ${{ secrets.DROPLET_IP }}
                  USERNAME: skullzarmy
              run: |
                  echo "$PRIVATE_KEY" > deploy_key
                  chmod 600 deploy_key
                  ssh -o StrictHostKeyChecking=no -i deploy_key $USERNAME@$HOST "
                  cd /home/skullzarmy/chatGPToot && 
                  git pull origin master && 
                  npm install &&
                  # Find and kill the existing processes
                  PIDS=\$(pgrep -f 'node app/chatgptoot.js')
                  for PID in \$PIDS; do
                      if [ ! -z \$PID ] && kill -0 \$PID 2>/dev/null; then 
                          kill \$PID
                      fi
                  done &&
                  # Start the new process
                  nohup node app/chatgptoot.js > logs/bot-log.log 2>&1 &
                  disown
                  echo "Bot started and disowned"
                  exit 0
                  "
                  echo "Removing deploy key"
                  rm -f deploy_key
