name: Deploy to DigitalOcean

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Deploy to DigitalOcean
              env:
                  PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
                  HOST: ${{ secrets.DROPLET_IP }}
                  USERNAME: skullzarmy
              run: |
                  echo "$PRIVATE_KEY" > deploy_key
                  chmod 600 deploy_key
                  ssh -o StrictHostKeyChecking=no -i deploy_key $USERNAME@$HOST "cd /home/skullzarmy/chatGPToot && git pull origin master"
                  ssh -o StrictHostKeyChecking=no -i deploy_key $USERNAME@$HOST "cd /home/skullzarmy/chatGPToot && npm install"
                  ssh -o StrictHostKeyChecking=no -i deploy_key $USERNAME@$HOST "
                  PIDS=\$(pgrep -f 'node app/chatgptoot.js')
                  for PID in \$PIDS; do
                      if [ ! -z \$PID ] && kill -0 \$PID 2>/dev/null; then 
                          kill \$PID
                      fi
                  done"
                  ssh -o StrictHostKeyChecking=no -i deploy_key $USERNAME@$HOST "cd /home/skullzarmy/chatGPToot && nohup node app/chatgptoot.js > logs/bot-log.log 2>&1 &"
                  echo "Removing deploy key"
                  rm -f deploy_key
